name: Build Docker
on: [push] # 当有人 push 代码时触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        run: docker build . --file Dockerfile --tag my-flask-app:latest
      - name: Test
        run: echo "Docker build success!"
